[package]
name = "otr-data-processor-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.18"
dotenv = "0.15.0"
indicatif = "0.17.7"
reqwest = { version = "0.11.24", features = ["json"] }
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
chrono = {  version = "0.4.33", features = ["serde"] }
openskill = "0.0.1"
statrs = "0.16.0"

[dev-dependencies]
async-once-cell = "0.5.3"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
